baseURL = ''
defaultContentLanguage = 'bg'
languageCode = 'bg-BG'
title = 'cookmood блог'
theme = 'cookmood'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  logo_file = "cookmood.stream_logo.png"
  has_favicon = true
  prod_base_url = "https://cookmood.stream"

[params.header.default]
  description = "моят готварски блог"
  to_beginning = "Начало"
[params.footer.default]
  copyright_message = "Всички права запазени."
  copyright_links = [
    { text = "Vector Vectors by Vecteezy", link = "https://www.vecteezy.com/free-vector/vector" },
    { text = "Nature Vectors by Vecteezy", link = "https://www.vecteezy.com/free-vector/nature" },
  ]
[params.footer.social]
  follow_facebook_url = ""
  follow_instagram_url = ""
  follow_twitter_url = ""
  follow_rss_url = "/index.xml"
[params.single]
  enable_social_share = true
[params.contact.default]
  label_name = "Вашето име"
  label_email = "Вашият email"
  label_message = "Вашето съобщение"
  label_button = "Изпрати"
[params.contact]
  action = "/.netlify/functions/form_contact"
[params.e404]
  message = "Съдържанието не е открито."
