baseURL = ""
languageCode = "bg-BG"
title = "cookmood - готварски блог"
copyright = "съдържание: автор на блога, лого: hati.royani & sunar.ko от vecteezy.com"

theme = "ananke"

DefaultContentLanguage = "bg"
SectionPagesMenu = "main"
Paginate = 5
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "images/cookmood.stream_logo.png"
  description = "Блог посветен на хитри рецепти"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = ""
  recent_posts_number = 2
